# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0289a4a9a41fee4415a90e528c72bcfd42b20d4967db8873e0fca430302b5ea4c2100235a0ce02f728a07af74f76181144111c87824deaf1f57d315854aed441
  google_client_id: '891649385891-cr97feh2b828g87c3djfouuhrq3mmgpi.apps.googleusercontent.com'
  google_client_secret: 'N1C8kwNfPXTrgbM-rAUANO34'

test:
  secret_key_base: a28a07aff7a4d9f2ccb0b19ebe3b31cfa0d0f1c38841c0259caa0734cd346467bb500ec3682b69208e5c694db6885fecb561f3ece839df5bdc3900d8b94bc687

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
